steps:
  - id: "Teste unitário"
    name: 'golang'
    args: ['go', 'test', './src']

  - id: "Build image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA', '.']
